apiVersion: v1
items:
- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"k8s.cni.cncf.io/v1","kind":"NetworkAttachmentDefinition","metadata":{"annotations":{},"name":"ovs-network","namespace":"default"},"spec":{"config":"{ \"cniVersion\": \"0.4.0\", \"type\": \"ovs\", \"bridge\": \"br0\" }"}}
    creationTimestamp: "2026-07-08T11:37:05Z"
    generation: 1
    name: ovs-network
    namespace: default
    resourceVersion: "9573"
    uid: 710082c6-0a31-4141-852a-556ae5b64638
  spec:
    config: '{ "cniVersion": "0.4.0", "type": "ovs", "bridge": "br0" }'
kind: List
metadata:
  resourceVersion: ""
