#!/usr/bin/env python3
"""
OVS Flow Parser - Converts OVS text flow dumps to JSON format

Usage:
    cat flows_raw.txt | python3 flows_parser.py > verification_flows.json
    python3 flows_parser.py --bundle output/ --bridge ovs-br0 > verification_flows.json
"""

import sys
import json
import re
import argparse
from pathlib import Path


def parse_flow_line(line):
    """Parse a single OVS flow rule line into structured format"""
    line = line.strip()
    if not line or line.startswith(("NXST_FLOW", "OFPST_FLOW", "OFPT_")):
        return None
    
    left, _, actions_str = line.partition(" actions=")
    info, match = {}, {}
    info_keys = {"cookie", "duration", "table", "n_packets", "n_bytes",
                 "idle_age", "hard_age", "priority", "idle_timeout", "hard_timeout"}
    
    for part in left.split(", "):
        if "=" not in part:
            continue
        k, v = part.split("=", 1)
        if k == "duration" and v.endswith("s"):
            v = float(v[:-1])
        elif re.fullmatch(r"-?\d+", v):
            v = int(v)
        (info if k in info_keys else match)[k] = v
    
    return {
        "orig": line,
        "info": info,
        "match": match,
        "actions": actions_str.strip()
    }


def parse_datapath_line(line):
    """Parse kernel datapath megaflow line"""
    line = line.strip()
    if not line:
        return None
    
    packets = bytes_val = used_s = None
    if "packets:" in line:
        m = re.search(r"packets:(\d+)", line)
        if m:
            packets = int(m.group(1))
    if "bytes:" in line:
        m = re.search(r"bytes:(\d+)", line)
        if m:
            bytes_val = int(m.group(1))
    if "used:" in line:
        m = re.search(r"used:([\d.]+)s", line)
        if m:
            used_s = float(m.group(1))
    
    # Extract actions
    actions = ""
    if "actions:" in line:
        actions = line.split("actions:")[-1].strip()
    
    return {
        "orig": line,
        "packets": packets,
        "bytes": bytes_val,
        "used_s": used_s,
        "actions": actions
    }


def parse_fdb_line(line):
    """Parse FDB (MAC learning table) line"""
    line = line.strip()
    if not line or line.startswith("port"):
        return None
    
    parts = line.split()
    if len(parts) >= 4:
        return {
            "port": int(parts[0]),
            "vlan": int(parts[1]),
            "mac": parts[2],
            "age_s": int(parts[3])
        }
    return None


def main():
    parser = argparse.ArgumentParser(description="Parse OVS flows to JSON")
    parser.add_argument("--bundle", help="Directory with evidence files")
    parser.add_argument("--bridge", default="ovs-br0", help="Bridge name")
    args = parser.parse_args()
    
    if args.bundle:
        # Read from evidence bundle
        bundle_path = Path(args.bundle)
        
        flows = []
        flows_file = bundle_path / "flows_raw.txt"
        if flows_file.exists():
            with open(flows_file) as f:
                flows = [parse_flow_line(l) for l in f]
                flows = [f for f in flows if f]
        
        datapath_flows = []
        datapath_file = bundle_path / "datapath_raw.txt"
        if datapath_file.exists():
            with open(datapath_file) as f:
                datapath_flows = [parse_datapath_line(l) for l in f]
                datapath_flows = [d for d in datapath_flows if d]
        
        fdb = []
        fdb_file = bundle_path / "fdb.txt"
        if fdb_file.exists():
            with open(fdb_file) as f:
                fdb = [parse_fdb_line(l) for l in f]
                fdb = [f for f in fdb if f]
        
        result = {
            "_meta": {
                "bridge": args.bridge,
                "note": "Generated by flows_parser.py from evidence bundle"
            },
            "flows": flows,
            "datapath_flows": datapath_flows,
            "fdb": fdb
        }
    else:
        # Read flows from stdin
        flows = [parse_flow_line(l) for l in sys.stdin]
        flows = [f for f in flows if f]
        result = {
            "_meta": {"bridge": args.bridge},
            "flows": flows
        }
    
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
